[package]
name = "ecosystem"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.87"
thiserror = "1.0.63"
tracing-appender = "0.2.3"

[dev-dependencies]
serde = "1.0.210"
axum = { version = "0.7.5", features = ["http2", "query", "tracing"] }
tokio = { version = "1.40.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde_json = "1.0.128"
