[package]
name = "ecosystem"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.87"
thiserror = "1.0.63"
tracing-appender = "0.2.3"
tokio = { version = "1.38.0", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "macros",
    "fs",
] }
derive_builder = "0.20.1"
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
serde_with = "3.9.0"

[dev-dependencies]
axum = { version = "0.7.5", features = ["http2", "query", "tracing"] }

tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
serde_json = "1.0.128"
http = "1.1.0"
bytes = "1.7.1"
blake3 = "1.5.4"
dashmap = "6.1.0"
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.12", features = ["codec"] }
futures = "0.3.30"
console-subscriber = "0.4.0"
