### index handler
GET http://localhost:8080/

### update handler
PATCH http://localhost:8081/
Content-Type: application/json

{
    "age": 21,
    "skills": [
        "Rust"
    ]
}

### index handler
GET http://localhost:9876/

### url shortener
POST http://localhost:9876/
Content-Type: application/json

{
    "url": "http://baidu.com"
}

### url redirect
GET http://localhost:9876/rveh9v

### proxy handler
GET http://localhost:6193/health
# get ->  HTTP/1.1 200 OK
# content-type: text/plain; charset=utf-8
# content-length: 48
# Date: Tue, 03 Dec 2024 11:50:25 GMT
# Name: Jack
# Connection: keep-alive

# Up, answered from 0.0.0.0:3000 with 0.0.0.0:6193

### validate valid
POST http://localhost:8080/hello_user
Content-Type: application/json

{
    "name": "Meng",
    "age": 20,
    "email": "Meng@123.com",
    "my_address": "四川成都"
}

### validate name invalid
POST http://localhost:8080/hello_user
Content-Type: application/json

{
    "name": "admin",
    "age": 20,
    "email": "Meng@123.com",
    "my_address": "四川成都"
}

### validate email invalid
POST http://localhost:8080/hello_user
Content-Type: application/json

{
    "name": "Meng",
    "age": 20,
    "email": "Meng",
    "my_address": "四川成都"
}

### validate age invalid
POST http://localhost:8080/hello_user
Content-Type: application/json

{
    "name": "Meng",
    "age": 17,
    "email": "Meng",
    "my_address": "四川成都"
}

### axum next
GET http://localhost:8080

# HTTP/1.1 200 OK
# content-type: text/plain; charset=utf-8
# server-time: 42us
# content-length: 5
# date: Mon, 03 Feb 2025 11:23:36 GMT

# Hello
